version: '3.8'

services:
  database:
    image: postgres:15.4
    env_file:
      - ./db.env
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ../db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432