// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.24.2
// source: internal/ports/grpc/task.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ports_grpc_task_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ports_grpc_task_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_internal_ports_grpc_task_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ports_grpc_task_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ports_grpc_task_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_internal_ports_grpc_task_proto_rawDescGZIP(), []int{1}
}

type TaskTypesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskTypes []*TaskTypesResponse_TaskTypes `protobuf:"bytes,1,rep,name=taskTypes,proto3" json:"taskTypes,omitempty"`
}

func (x *TaskTypesResponse) Reset() {
	*x = TaskTypesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ports_grpc_task_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTypesResponse) ProtoMessage() {}

func (x *TaskTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ports_grpc_task_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTypesResponse.ProtoReflect.Descriptor instead.
func (*TaskTypesResponse) Descriptor() ([]byte, []int) {
	return file_internal_ports_grpc_task_proto_rawDescGZIP(), []int{2}
}

func (x *TaskTypesResponse) GetTaskTypes() []*TaskTypesResponse_TaskTypes {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

type TaskTypesResponse_TaskTypes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id       int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	IsActive bool   `protobuf:"varint,3,opt,name=isActive,proto3" json:"isActive,omitempty"`
}

func (x *TaskTypesResponse_TaskTypes) Reset() {
	*x = TaskTypesResponse_TaskTypes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_ports_grpc_task_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskTypesResponse_TaskTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTypesResponse_TaskTypes) ProtoMessage() {}

func (x *TaskTypesResponse_TaskTypes) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ports_grpc_task_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTypesResponse_TaskTypes.ProtoReflect.Descriptor instead.
func (*TaskTypesResponse_TaskTypes) Descriptor() ([]byte, []int) {
	return file_internal_ports_grpc_task_proto_rawDescGZIP(), []int{2, 0}
}

func (x *TaskTypesResponse_TaskTypes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskTypesResponse_TaskTypes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TaskTypesResponse_TaskTypes) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_internal_ports_grpc_task_proto protoreflect.FileDescriptor

var file_internal_ports_grpc_task_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x73,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xa1, 0x01, 0x0a, 0x11, 0x54, 0x61, 0x73, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a,
	0x09, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x52, 0x09, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x4b,
	0x0a, 0x09, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x32, 0x45, 0x0a, 0x04, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x3d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x73, 0x12, 0x12, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_ports_grpc_task_proto_rawDescOnce sync.Once
	file_internal_ports_grpc_task_proto_rawDescData = file_internal_ports_grpc_task_proto_rawDesc
)

func file_internal_ports_grpc_task_proto_rawDescGZIP() []byte {
	file_internal_ports_grpc_task_proto_rawDescOnce.Do(func() {
		file_internal_ports_grpc_task_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_ports_grpc_task_proto_rawDescData)
	})
	return file_internal_ports_grpc_task_proto_rawDescData
}

var file_internal_ports_grpc_task_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_ports_grpc_task_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil),                // 0: task.EmptyRequest
	(*EmptyResponse)(nil),               // 1: task.EmptyResponse
	(*TaskTypesResponse)(nil),           // 2: task.TaskTypesResponse
	(*TaskTypesResponse_TaskTypes)(nil), // 3: task.TaskTypesResponse.TaskTypes
}
var file_internal_ports_grpc_task_proto_depIdxs = []int32{
	3, // 0: task.TaskTypesResponse.taskTypes:type_name -> task.TaskTypesResponse.TaskTypes
	0, // 1: task.Task.GetTaskTypes:input_type -> task.EmptyRequest
	2, // 2: task.Task.GetTaskTypes:output_type -> task.TaskTypesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_ports_grpc_task_proto_init() }
func file_internal_ports_grpc_task_proto_init() {
	if File_internal_ports_grpc_task_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_ports_grpc_task_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ports_grpc_task_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ports_grpc_task_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskTypesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_ports_grpc_task_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskTypesResponse_TaskTypes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_ports_grpc_task_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_ports_grpc_task_proto_goTypes,
		DependencyIndexes: file_internal_ports_grpc_task_proto_depIdxs,
		MessageInfos:      file_internal_ports_grpc_task_proto_msgTypes,
	}.Build()
	File_internal_ports_grpc_task_proto = out.File
	file_internal_ports_grpc_task_proto_rawDesc = nil
	file_internal_ports_grpc_task_proto_goTypes = nil
	file_internal_ports_grpc_task_proto_depIdxs = nil
}
